version: '3.8'  # specify the version of docker-compose

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: hardtack-weaviate
    ports:
      - "8080:8080"  # REST API port
      - "50051:50051"  # gRPC port
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/data/weaviate"  # must match the internal container path
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
    volumes:
      - /Users/arrakis/analytics/hardtack/data/weaviate:/data/weaviate
    restart: unless-stopped  # ensure it restarts on failure or reboot